### ISSUE TITLE
Problems when using `num_workers` in Pytorch on MacOS

### ISSUE THREAD

**Issue by thomkeh** [neptune-ai/neptune-client#285] opened 2020-10-19 19:10 UTC
I have code like this:

```python
from torch.utils.data import DataLoader
# ...
def main():
    # ...
    train_loader = DataLoader(
        datasets.train,
        shuffle=True,
        batch_size=ARGS.batch_size,
        num_workers=ARGS.num_workers,
        pin_memory=True,
    )
```
where `num_worker` determines with how many threads pytorch reads the data. If this is set to 0, then pytorch reads the data in the main thread. On MacOS, setting it to any other value than 0 seems to mess up neptune (the problem does not seem to appear on Linux; I have not tried Windows).

What seems to happen is that neptune starts a new experiment for each worker (this is with `num_workers=4`):
```
https://ui.neptune.ai/tmk/fcm/e/FCM-38
https://ui.neptune.ai/tmk/fcm/e/FCM-39
https://ui.neptune.ai/tmk/fcm/e/FCM-40
https://ui.neptune.ai/tmk/fcm/e/FCM-41
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/tk324/anaconda/envs/pytorch/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/tk324/anaconda/envs/pytorch/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Users/tk324/anaconda/envs/pytorch/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/tk324/anaconda/envs/pytorch/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Users/tk324/anaconda/envs/pytorch/lib/python3.8/runpy.py", line 263, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/tk324/anaconda/envs/pytorch/lib/python3.8/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/tk324/anaconda/envs/pytorch/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/tk324/PycharmProjects/fair-dist-matching/run_clust.py", line 4, in <module>
    main()
  File "/Users/tk324/PycharmProjects/fair-dist-matching/clustering/optimisation/train.py", line 170, in main
    input_shape = get_data_dim(context_loader)
  File "/Users/tk324/PycharmProjects/fair-dist-matching/shared/utils/utils.py", line 44, in get_data_dim
    x = next(iter(data_loader))[0]
  File "/Users/tk324/anaconda/envs/pytorch/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 291, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "/Users/tk324/anaconda/envs/pytorch/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 737, in __init__
    w.start()
  File "/Users/tk324/anaconda/envs/pytorch/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/tk324/anaconda/envs/pytorch/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Users/tk324/anaconda/envs/pytorch/lib/python3.8/multiprocessing/context.py", line 283, in _Popen
    return Popen(process_obj)
  File "/Users/tk324/anaconda/envs/pytorch/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/tk324/anaconda/envs/pytorch/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/tk324/anaconda/envs/pytorch/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/Users/tk324/anaconda/envs/pytorch/lib/python3.8/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/Users/tk324/anaconda/envs/pytorch/lib/python3.8/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "/Users/tk324/anaconda/envs/pytorch/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 779, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/Users/tk324/anaconda/envs/pytorch/lib/python3.8/multiprocessing/queues.py", line 107, in get
    if not self._poll(timeout):
  File "/Users/tk324/anaconda/envs/pytorch/lib/python3.8/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "/Users/tk324/anaconda/envs/pytorch/lib/python3.8/multiprocessing/connection.py", line 424, in _poll
    r = wait([self], timeout)
  File "/Users/tk324/anaconda/envs/pytorch/lib/python3.8/multiprocessing/connection.py", line 930, in wait
    ready = selector.select(timeout)
  File "/Users/tk324/anaconda/envs/pytorch/lib/python3.8/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
  File "/Users/tk324/anaconda/envs/pytorch/lib/python3.8/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 53749) exited unexpectedly with exit code 1. Details are lost due to multiprocessing. Rerunning with num_workers=0 may give better error trace.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_clust.py", line 4, in <module>
    main()
  File "/Users/tk324/PycharmProjects/fair-dist-matching/clustering/optimisation/train.py", line 170, in main
    input_shape = get_data_dim(context_loader)
  File "/Users/tk324/PycharmProjects/fair-dist-matching/shared/utils/utils.py", line 44, in get_data_dim
    x = next(iter(data_loader))[0]
  File "/Users/tk324/anaconda/envs/pytorch/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/Users/tk324/anaconda/envs/pytorch/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 974, in _next_data
    idx, data = self._get_data()
  File "/Users/tk324/anaconda/envs/pytorch/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 941, in _get_data
    success, data = self._try_get_data()
  File "/Users/tk324/anaconda/envs/pytorch/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 792, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str))
RuntimeError: DataLoader worker (pid(s) 53749) exited unexpectedly
```

With `num_workers=0`, this runs fine.

**Comment by hubertjaworskineptune** [comment] 2020-10-21 08:44
Hi,

Thank you for reporting this.

Can you confirm that this problem occurs only when you use Neptune and works without it?

Your stacktrace does not point to anything Neptune-related and is awfully similar to https://github.com/pytorch/pytorch/issues/28820

It seems that this is an issue with pytorch and not Neptune - in the Pytorch issue users mentioned two things that helped them:
- when using docker images to add `--shm-size = your size G` 
- when running on Mac, add `cv2.setNumThreads(0)` at the start of script

Let us know if that helped

Best Regards,
Hubert Jaworski

**Comment by PiotrJander** [comment] 2020-10-21 10:04
Hi @thomkeh , we reported the issue to `pytorch` maintainers: https://github.com/pytorch/pytorch/issues/46648 . We're closing this since this is not Neptune related.

But you if you have a reproducible piece of code which runs well without Neptune and only breaks with Neptune, please re-open this issue.

**Closed by PiotrJander** 2020-10-21 10:04 UTC

**Comment by thomkeh** [comment] 2020-10-21 10:33
Hi, I was able to reproduce it without Neptune. So you were right. Sorry about that!

**Comment by PiotrJander** [comment] 2020-10-21 21:24
Hi @thomkeh , the answer we got from PyTorch Lightning maintainers might help you: https://github.com/PyTorchLightning/pytorch-lightning/issues/4289
