### ISSUE TITLE
BUG: self.logger.experiment error

### ISSUE THREAD

**Issue by zhiyuanpeng** [neptune-ai/neptune-client#640] opened 2021-08-04 21:45 UTC
### Describe the bug
I use pytorch-lightning 1.3.8 and nuptune. After I pass nuptune logger to trainer. I can use self.log(logger=nuptune_logger) to log parameters to nuptune. But when I use self.logger.experiment to access the nuptune `Run` object, no matter what nuptune log methos I use, it throws the same error: `TypeError: list indices must be integers or slices, not str`.
### Reproduction
```
    def validation_epoch_end(self, outputs: List[Any]):
        data = {'col_1': [3, 2, 1, 0], 'col_2': ['a', 'b', 'c', 'd']}
        data_pd = pd.DataFrame.from_dict(data)
        data_html = File.as_html(data_pd)
        self.logger.experiment['val/report'].upload(data_html)
```
### Expected behavior
pandas dataframe will be logged to nuptune
### Traceback
```
Traceback (most recent call last):
  File "", line 30, in main
    return train(config)
  File "", line 77, in train
    trainer.fit(model=model, datamodule=datamodule)
  File "/home/zhiyuan/opt/anaconda3/envs/pltorch1.7.1/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 460, in fit
    self._run(model)
  File "/home/zhiyuan/opt/anaconda3/envs/pltorch1.7.1/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 758, in _run
    self.dispatch()
  File "/home/zhiyuan/opt/anaconda3/envs/pltorch1.7.1/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 799, in dispatch
    self.accelerator.start_training(self)
  File "/home/zhiyuan/opt/anaconda3/envs/pltorch1.7.1/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 96, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/home/zhiyuan/opt/anaconda3/envs/pltorch1.7.1/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 144, in start_training
    self._results = trainer.run_stage()
  File "/home/zhiyuan/opt/anaconda3/envs/pltorch1.7.1/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 809, in run_stage
    return self.run_train()
  File "/home/zhiyuan/opt/anaconda3/envs/pltorch1.7.1/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 844, in run_train
    self.run_sanity_check(self.lightning_module)
  File "/home/zhiyuan/opt/anaconda3/envs/pltorch1.7.1/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1112, in run_sanity_check
    self.run_evaluation()
  File "/home/zhiyuan/opt/anaconda3/envs/pltorch1.7.1/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 993, in run_evaluation
    self.evaluation_loop.evaluation_epoch_end(outputs)
  File "/home/zhiyuan/opt/anaconda3/envs/pltorch1.7.1/lib/python3.8/site-packages/pytorch_lightning/trainer/evaluation_loop.py", line 213, in evaluation_epoch_end
    model.validation_epoch_end(outputs)
  File "", line 150, in validation_epoch_end
    self.logger.experiment['val/f1'].log(f1)
TypeError: list indices must be integers or slices, not str
```
### Environment
**The output of `pip list`:**
```
Package                           Version         Location
--------------------------------- --------------- -------------------------------------------------------------------------
absl-py                           0.13.0
aiohttp                           3.7.4.post0
alembic                           1.6.5
allennlp                          2.5.0
antlr4-python3-runtime            4.8
appdirs                           1.4.4
argon2-cffi                       20.1.0
async-generator                   1.10
async-timeout                     3.0.1
atpublic                          2.3
attrs                             21.2.0
backcall                          0.2.0
backports.csv                     1.0.7
backports.entry-points-selectable 1.1.0
beautifulsoup4                    4.9.3
bleach                            3.3.1
blinker                           1.4
blis                              0.7.4
bravado                           11.0.3
bravado-core                      5.17.0
brotlipy                          0.7.0
cachetools                        4.2.2
catalogue                         2.0.4
certifi                           2021.5.30
cffi                              1.14.6
cfgv                              3.3.0
chardet                           4.0.0
checklist                         0.0.11
cheroot                           8.5.2
CherryPy                          18.6.1
click                             7.1.2
cliff                             3.8.0
cmaes                             0.8.2
cmd2                              2.1.2
colorama                          0.4.4
colorlog                          5.0.1
commonmark                        0.9.1
configobj                         5.0.6
configparser                      5.0.2
cryptography                      3.4.7
cycler                            0.10.0
cymem                             2.0.5
debugpy                           1.4.1
decorator                         5.0.9
defusedxml                        0.7.1
dictdiffer                        0.9.0
dill                              0.3.4
diskcache                         5.2.1
distlib                           0.3.2
distro                            1.5.0
docker-pycreds                    0.4.0
dpath                             2.0.1
dulwich                           0.20.24
dvc                               2.5.4
entrypoints                       0.3
feedparser                        6.0.8
filelock                          3.0.12
flatten-dict                      0.4.1
flufl.lock                        3.2
fsspec                            2021.7.0
ftfy                              6.0.3
funcy                             1.16
future                            0.18.2
gitdb                             4.0.7
GitPython                         3.1.18
google-api-core                   1.31.0
google-auth                       1.33.0
google-auth-oauthlib              0.4.4
google-cloud-core                 1.7.1
google-cloud-storage              1.38.0
google-crc32c                     1.1.2
google-resumable-media            1.3.1
googleapis-common-protos          1.53.0
grandalf                          0.6
greenlet                          1.1.0
grpcio                            1.38.1
h5py                              3.3.0
huggingface-hub                   0.0.8
hydra-colorlog                    1.1.0
hydra-core                        1.1.0
hydra-optuna-sweeper              1.1.0
identify                          2.2.11
idna                              2.10
importlib-metadata                4.6.1
importlib-resources               5.2.0
iniconfig                         1.1.1
ipykernel                         6.0.3
ipython                           7.25.0
ipython-genutils                  0.2.0
ipywidgets                        7.6.3
iso-639                           0.4.5
jaraco.classes                    3.2.1
jaraco.collections                3.3.0
jaraco.functools                  3.3.0
jaraco.text                       3.5.0
jedi                              0.18.0
Jinja2                            3.0.1
jmespath                          0.10.0
joblib                            1.0.1
jsonnet                           0.17.0
jsonpath-ng                       1.5.3
jsonpointer                       2.1
jsonref                           0.2
jsonschema                        3.2.0
jupyter                           1.0.0
jupyter-client                    6.1.12
jupyter-console                   6.4.0
jupyter-core                      4.7.1
jupyterlab-pygments               0.1.2
jupyterlab-widgets                1.0.0
kiwisolver                        1.3.1
lmdb                              1.2.1
lxml                              4.6.3
mailchecker                       4.0.11
Mako                              1.1.4
Markdown                          3.3.4
MarkupSafe                        2.0.1
matplotlib                        3.4.2
matplotlib-inline                 0.1.2
mccabe                            0.6.1
mistune                           0.8.4
mkl-fft                           1.3.0
mkl-random                        1.2.2
mkl-service                       2.4.0
monotonic                         1.5
more-itertools                    8.8.0
mpmath                            1.2.1
msgpack                           1.0.2
multidict                         5.1.0
munch                             2.5.0
murmurhash                        1.0.5
mypy-extensions                   0.4.3
nanotime                          0.5.2
nbclient                          0.5.3
nbconvert                         6.1.0
nbformat                          5.1.3
neptune-client                    0.10.2
neptune-notebooks                 0.9.0
neptune-pytorch-lightning         0.9.7
nest-asyncio                      1.5.1
networkx                          2.5.1
nltk                              3.6.2
nodeenv                           1.6.0
nose                              1.3.7
notebook                          6.4.0
numpy                             1.20.2
oauthlib                          3.1.1
olefile                           0.46
omegaconf                         2.1.0
optuna                            2.4.0
overrides                         3.1.0
packaging                         21.0
pandas                            1.2.4
pandocfilters                     1.4.3
parso                             0.8.2
path                              16.0.0
path.py                           12.5.0
pathspec                          0.8.1
pathtools                         0.1.2
pathy                             0.6.0
patternfork-nosql                 3.6
pbr                               5.6.0
pdfminer.six                      20201018
pexpect                           4.8.0
phonenumbers                      8.12.28
pickleshare                       0.7.5
Pillow                            8.2.0
pip                               21.1.3
platformdirs                      2.0.2
pluggy                            0.13.1
ply                               3.11
portend                           2.7.1
pre-commit                        2.13.0
preshed                           3.0.5
prettytable                       2.1.0
prometheus-client                 0.11.0
promise                           2.3
prompt-toolkit                    3.0.19
protobuf                          3.17.3
psutil                            5.8.0
ptyprocess                        0.7.0
pudb                              2021.1
py                                1.10.0
py3nvml                           0.2.5
pyasn1                            0.4.8
pyasn1-modules                    0.2.8
pycodestyle                       2.7.0
pycparser                         2.20
pydantic                          1.7.4
pyDeprecate                       0.3.0
pydot                             1.4.2
pyflakes                          2.3.1
pygit2                            1.6.1
Pygments                          2.9.0
pygtrie                           2.4.2
PyJWT                             2.1.0
pyOpenSSL                         20.0.1
pyparsing                         2.4.7
pyperclip                         1.8.2
pyrsistent                        0.18.0
pysbd                             0.3.4           /home/zhiyuan/Documents/proj/SemanticSearch/SSApp/app/parser_engine/pySBD
PySocks                           1.7.1
pytest                            6.2.4
python-benedict                   0.24.0
python-dateutil                   2.8.2
python-docx                       0.8.11
python-dotenv                     0.18.0
python-editor                     1.0.4
python-fsutil                     0.5.0
python-slugify                    5.0.2
pytorch-lightning                 1.3.8
pytz                              2021.1
PyUtilib                          6.0.0
PyYAML                            5.4.1
pyzmq                             22.1.0
qtconsole                         5.1.1
QtPy                              1.9.0
regex                             2021.7.6
requests                          2.25.1
requests-oauthlib                 1.3.0
rfc3987                           1.3.8
rich                              10.6.0
rsa                               4.7.2
ruamel.yaml                       0.17.10
ruamel.yaml.clib                  0.2.6
s3transfer                        0.4.2
sacremoses                        0.0.45
scikit-learn                      0.24.2
scikit-plot                       0.3.7
scipy                             1.7.0
seaborn                           0.11.1
Send2Trash                        1.7.1
sentencepiece                     0.1.96
sentry-sdk                        1.3.0
seqeval                           1.2.2
setuptools                        57.4.0
sgmllib3k                         1.0.0
shortuuid                         1.0.1
shtab                             1.3.9
simplejson                        3.17.3
six                               1.16.0
smart-open                        5.1.0
smmap                             4.0.0
sortedcontainers                  2.4.0
soupsieve                         2.2.1
spacy                             3.0.6
spacy-legacy                      3.0.8
SQLAlchemy                        1.4.21
srsly                             2.4.1
stevedore                         3.3.0
strict-rfc3339                    0.7
subprocess32                      3.5.4
swagger-spec-validator            2.7.3
sympy                             1.8
tabulate                          0.8.9
tempora                           4.1.1
tensorboard                       2.4.1
tensorboard-plugin-wit            1.8.0
tensorboardX                      2.4
termcolor                         1.1.0
terminado                         0.10.1
testpath                          0.5.0
text-unidecode                    1.3
thinc                             8.0.7
threadpoolctl                     2.2.0
tokenizers                        0.10.3
toml                              0.10.2
torch                             1.7.1
torchaudio                        0.7.0a0+a853dff
torchmetrics                      0.4.1
torchvision                       0.8.2
tornado                           6.1
tqdm                              4.61.2
traitlets                         5.0.5
transformers                      4.6.1
typer                             0.3.2
typing-extensions                 3.10.0.0
urllib3                           1.26.6
urwid                             2.1.2
virtualenv                        20.6.0
voluptuous                        0.12.1
wandb                             0.10.33
wasabi                            0.8.2
wcwidth                           0.2.5
webcolors                         1.11.1
webencodings                      0.5.1
websocket-client                  0.57.0
Werkzeug                          2.0.1
wheel                             0.36.2
widgetsnbextension                3.5.1
xmltodict                         0.12.0
yarl                              1.6.3
zc.lockfile                       2.0
zipp                              3.5.0

```
**The operating system you're using:**
Ubuntu 20.04
**The output of `python --version`:**
Python 3.8.10

**Comment by Blaizzy** [comment] 2021-08-05 16:21
Hi 

I'm Prince Canuma a Data Scientist and DevRel at Neptune.ai,

I have attempted to reproduce your error and I noticed 2 things:

1. You are using `pytorch-lightening v1.3.8`  and `neptune-client v0.10.2`  try and import the NeptuneLogger this way:
               - `from neptune.new.integrations.pytorch_lightning import NeptuneLogger` 
Instead of importing from lightning because v1.3.8 uses the legacy  neptune-client by default while your code follows the new neptune-client.
If you make this change you will see that your code example will run!

2. The `TypeError: list indices must be integers or slices, not str` is perhaps related with your argument `outputs`. I found this link on stackoverflow I hope it helps point you in the right direction.
                - Stackoverflow[list indices must be integets or slices, not str](https://stackoverflow.com/questions/35957085/python3-typeerror-list-indices-must-be-integers-or-slices-not-str
)


Let me know if this solves your problem,

Regards

**Comment by zhiyuanpeng** [comment] 2021-08-05 18:11
@Blaizzy Thanks for your reply.

I import `NeptuneLogger` from `neptune.new.integrations.pytorch_lightning` but still the same `list indices must be integets or slices, not str` error.

I run the code in [Neptune pandas](https://docs.neptune.ai/integrations-and-supported-tools/model-visualization-and-debugging/pandas):

```
iris_df = pd.read_csv(
            'https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv',
            nrows=100)
        self.logger.experiment['val/report'].upload(File.as_html(iris_df)
```

The error trace:

```
    self.logger.experiment['val/report'].upload(File.as_html(iris_df))
TypeError: list indices must be integers or slices, not str
```

**Comment by zhiyuanpeng** [comment] 2021-08-05 20:32
@Blaizzy Hi Blaizzy, I find the bug:

Pytorch lightning can accept a list of loggers, so in my code:
```
    # Init lightning loggers
    logger: List[LightningLoggerBase] = []
    if "logger" in config:
        for _, lg_conf in config.logger.items():
            if "_target_" in lg_conf:
                log.info(f"Instantiating logger <{lg_conf._target_}>")
                logger.append(hydra.utils.instantiate(lg_conf)
```
In function `validation_epoch_end`, I access the `Run` obj by:
```
self.logger.experiment['data/iris-df'].upload(File.as_html(iris_df))
``

Actually, it should be:
```
self.logger.experiment[0]['data/iris-df'].upload(File.as_html(iris_df))
```

**Comment by Blaizzy** [comment] 2021-08-06 06:55
Great news!!! Well done 👍 . 

I wasn't aware you had a list of loggers.

I will be closing this issue. But let me know if there is anything else I can help you with!

**Closed by Blaizzy** 2021-08-06 06:55 UTC
