### ISSUE TITLE
Interference between Neptune and Ray causes processes to hang 

### ISSUE THREAD

**Issue by thatGreekGuy96** [neptune-ai/neptune-client#379] opened 2021-01-31 18:19 UTC
Hello everyone! 
We're starting to use neptune to log a bunch of metrics related to optimisation runs using evolutionary computing techniques. We use the [Ray](https://docs.ray.io/en/master/) framework to parallelise large parts of our code. 

We noticed that our scripts would hang fairly often when using Ray. When running an experiment, all the data is uploaded to neptune, and the experiment is marked as completed, but the process ahngs and does not exit. This happened consistently on different local machines (Mac OS 11, Ubuntu) and on different k8s pods. 

After a lot of digging around, we noticed that the issue was resolved by setting the `upload_stderr` argument to `False` when calling the `create_experiment` function. 

This is not a huge deal for us, but I am just letting you know in case there is an easy fix!

**Comment by PiotrJander** [comment] 2021-02-01 09:22
Hi, thanks for letting us know! We suspect what the problem might be, and we'll keep you updated as we verify this hypothesis.

**Comment by PiotrJander** [comment] 2021-02-01 13:09
@thatGreekGuy96 , we couldn't reproduce the problem you're having using a very minimal example of neptune and ray - could you provide us with a minimal example which reproduces the problem? Thanks!

**Comment by thatGreekGuy96** [comment] 2021-02-01 21:39
I'll try to get that for you asap!

**Comment by thatGreekGuy96** [comment] 2021-02-03 09:58
@PiotrJander unfortunately i have not managed to reproduce this exact error. This must mean that there are other bits of our code that are causing this behaviour. I did however notice something strange when trying to make a minimal example with neptune and ray. 

When running the script below:
```python3
import neptune
import time
import ray
import neptune


@ray.remote
class ARayActor:

    def __init__(self, a, experiment_id):
        self.a = a
        session = neptune.Session.with_default_backend()
        project = session.get_project("Continuum-Industries/dev")
        self._experiment = project.get_experiments(experiment_id)[0]

    def calculate_something(self):
        time.sleep(0.5)
        self._experiment.log_metric(str(self.a), self.a+1)


ray.init()
neptune.init("Continuum-Industries/dev")
experiment = neptune.create_experiment("test")

actors = [ARayActor.remote(i, experiment.id) for i in range(1)]
f = [a.calculate_something.remote() for a in actors]
```

I get the following interesting error:
```
andreas@andyMac ~/Desktop> python test_neptune.py                                                                                                                                                                                                                                                                                                                                                                    
2021-02-03 09:57:11,994 INFO resource_spec.py:204 -- Starting Ray with 9.81 GiB memory available for workers and up to 4.92 GiB for objects. You can adjust these settings with ray.init(memory=<bytes>, object_store_memory=<bytes>).
2021-02-03 09:57:12,334 INFO services.py:1146 -- View the Ray dashboard at localhost:8265
Your trial will end in 1 day. If you want to continue tracking your team experiments in Neptune, upgrade your plan (https://ui.neptune.ai/o/Continuum-Industries/-/subscription)
Info (NVML): NVML Shared Library Not Found. GPU usage metrics may not be reported. For more information, see https://docs.neptune.ai/logging-and-managing-experiment-results/logging-experiment-data.html#hardware-consumption 
https://ui.neptune.ai/Continuum-Industries/dev/e/DEV-47
(pid=484) Your trial will end in 1 day. If you want to continue tracking your team experiments in Neptune, upgrade your plan (https://ui.neptune.ai/o/Continuum-Industries/-/subscription)
Exception ignored in: <function ActorHandle.__del__ at 0x7fec20e66f70>
Traceback (most recent call last):
  File "/Users/andreas/anaconda3/envs/poddie/lib/python3.8/site-packages/ray/actor.py", line 657, in __del__
AttributeError: 'NoneType' object has no attribute 'global_worker
```

Maybe this is related? If not i can open a separate issue for it.

**Comment by PiotrJander** [comment] 2021-02-03 11:29
Thanks, that gives us a starting point for investigation - we'll keep you updated!

**Comment by thatGreekGuy96** [comment] 2021-02-03 11:35
Awesome! Something i forgot to clarify, the script i just posted exits, and the expected test data is written on Neptune. This error appears at the very end, when I assume that both Neptune and Ray try to shut down and close everything.

**Comment by pkasprzyk** [comment] 2021-08-09 14:54
@thatGreekGuy96 I'm sorry it took us that long to get back to this issue. We've made quite a log of changes with error/state reporting in client (printing info about lost connection, especially verbose procedure for finishing run) and fixed a bug with some multiprocessing scenarios not finishing up.
Are you by chance still using neptune? Do you encounter any problems?

**Comment by thatGreekGuy96** [comment] 2021-08-25 14:07
Hello @pkasprzyk , we're very much still using neptune and we really like it so far! 

We moved to neptune.new a couple of months ago and all the issues we had related to this disappeared, so I think the problem fixed itself hehe

**Comment by pkasprzyk** [comment] 2021-08-25 14:22
Thanks for replying, and I'm very happy you're experience is positive now :)

Closing the issue -- though don't hesitate to reach out in the future, of course!

**Closed by pkasprzyk** 2021-08-25 14:22 UTC
