### ISSUE TITLE
Feature Request: Disable neptune for local development

### ISSUE THREAD

**Issue by hydrocat** [neptune-ai/neptune-client#1541] opened 2023-10-20 15:06 UTC
### Is your feature request related to a problem? Please describe.
Whenever we are trying out something unrelated to ML dev such as, pipelines, deployment, container, packaging, we would like to try running our code which uses neptune without configuring api tokens, project and everything else.

### Describe the solution you'd like
A new `mode` that disables neptune. No requests, nothing. 
### Describe alternatives you've considered
We tried `debug` mode:
```python
import neptune

run = neptune.init_run(mode="debug")
```
but it fails with:
```
neptune.exceptions.RunNotFound: Run <project-name>/OFFLINE-1 not found.
```

**Comment by SiddhantSadangi** [comment] 2023-10-20 15:14
Hey @hydrocat 👋 

I am not able to reproduce this error. Initializing a run in `debug` mode in a new environment (a fresh colab notebook) without any configuration does not throw any error for me.

Did you run neptune in `offline` mode prior to this? Can you try first deleting the `.neptune` folder in the `cwd` and then initiazing a run in `debug` mode?

**Comment by hydrocat** [comment] 2023-10-23 19:11
Hey ! thanks for the reply !

Upon further exploration, it seems that the 'debug mode' requires a valid api token and valid project name.

Am I missing something ?

**Comment by SiddhantSadangi** [comment] 2023-10-23 19:23
Hey,
The `debug` mode should not require any API token or project name.

To confirm, I ran the below in a fresh colab notebook, and it didn't  throw any error:
![image](https://github.com/neptune-ai/neptune-client/assets/41324509/2076e358-9f3a-4d76-b35c-859c9ffc17bb)

Can you share the exact traceback?

**Comment by hydrocat** [comment] 2023-10-25 16:12
Há, I've got it !

The thing is that you can't start a run with the argument `with_id` and pass in a wrong value.

Properly setting up the initial run and then passing its id to subsequent runs works like a charm.

However, the error message is fairly misleading.

instead of throwing
```
neptune.exceptions.RunNotFound: Run <project-name>/OFFLINE-1 not found.
```

something like this _might_ be better.
```
neptune.exceptions.RunNotFound: Run with ID <project-name>/OFFLINE-1 not found.
```

In hindsight `RunNotFound` does make sense, but the automatically generated id, doesn't help either.

**Comment by SiddhantSadangi** [comment] 2023-10-25 16:36
Thanks for sharing the details!
Since Neptune already behaves the way you wanted it to in `debug` mode, I am closing this feature request.

However, I would still like to collect some feedback 🙂

When you say "automatically generated ID", are you referring to the RUN ID being automatically generated, or the ID displayed in the error message being automatically generated?

I tested the error and it looks like the format is `neptune.exceptions.RunNotFound: Run <your-workspace>/<your-project>/<id-passed-in-with-id> not found.` 

Do you have suggestions on how we could improve this and make it more intuitive for our users? 🤗

**Closed by SiddhantSadangi** 2023-10-25 16:36 UTC
Labels: pending
