### ISSUE TITLE
BUG: NeptuneLogger version (_run_short_id) returns None

### ISSUE THREAD

**Issue by AlexTo** [neptune-ai/neptune-client#1697] opened 2024-03-17 00:09 UTC
### Describe the bug
When using NeptuneLogger, the `version` property returns None

### Reproduction
Neptune: 1.9.1
Pytorch-lightning: 1.9.5

Just use a neptune_logger with pl.Trainer as in the integration example

```
neptune_logger = (
        NeptuneLogger(
            name=model.name,
            description=model.description,
            source_files=[],
            log_model_checkpoints=False,
        )
    )

trainer = pl.Trainer(
        ...
        logger=neptune_logger
    )
...
```

The `version` from NeptuneLogger is always `None` resulting in the folder created to store the checkpoints appear as `None`

![image](https://github.com/neptune-ai/neptune-client/assets/296212/93bbc508-d149-4ef0-85f2-fbf0b240a979)

The weird thing is if also in the Debug Console above, I type `self` (which is the instance of NeptuneLogger currently being debugged) and then use the `expand arrow` to expand the NeptuneLogger instance (see below screenshot) , then the instance seems to load something (or "refresh" itself), and then the `_run_short_id` is no longer None.

![image](https://github.com/neptune-ai/neptune-client/assets/296212/a02499cf-fcc2-4061-b161-993070e3b51f)

Now, the `_run_short_id` has a value (which is GP-45)

![image](https://github.com/neptune-ai/neptune-client/assets/296212/bec5cee7-1348-49b1-929a-28b44cf50791)

Anyone having similar issue?

Thank you

**Comment by SiddhantSadangi** [comment] 2024-03-18 09:03
Hey @AlexTo 👋 

Can you help me understand what the issue here is?

The folder created to store uploaded model checkpoints is always `model/checkpoints`, and is not related to `run_short_id`.
Also, the run ID is created only once the run has been initialized in the `sync`/`async` mode.

Is this not what you are expecting?

**Comment by AlexTo** [comment] 2024-03-18 13:54
hi @SiddhantSadangi 

I'm using Neptune 1.9.1 and Pytorch Lightning 1.9.5 with ModelCheckpoint

They use the `version` property from `NeptuneLogger` as in this [line](https://github.com/Lightning-AI/pytorch-lightning/blob/1.9.5/src/pytorch_lightning/callbacks/model_checkpoint.py#L591) to construct the checkpoint path.

However, I also just realized that `NeptuneLogger` is a wrapper class from Pytorch Lightning and not from Neptune. 

Probably false alarm, thanks for your response. I think I need to look into their wrapper class to see where the bug comes from.

**Comment by SiddhantSadangi** [comment] 2024-03-18 14:08
Thanks for the update!

As seen [here](https://github.com/Lightning-AI/pytorch-lightning/blob/a020506a81a671e380872aa5e435647b549e14e6/src/pytorch_lightning/loggers/neptune.py#L484), the path where model checkpoints are uploaded to Neptune is hardcoded to `model/checkpoints`, so you should not be seeing the checkpoints being uploaded to the `None` folder. Please let me know if this is the case though.

**Comment by AlexTo** [comment] 2024-03-19 05:10
As mentioned above, I'm using `ModelCheckpoint` so I guess it is a bit different. From the code snippet in my comment, here is how the ModelCheckpoint construct the checkpoint path

<img width="620" alt="image" src="https://github.com/neptune-ai/neptune-client/assets/296212/90aca485-8b11-4b75-b453-276cca58fa9b">

So, for me, the folder created is like this `version = trainer.loggers[0].version` 

`.neptune/model_name/version_None/checkpoints` 

because `trainer.loggers[0].version` which is `NeptuneLogger.version` returns `None`. 

I'll debug the `NeptuneLogger` in the next 1 or 2 days and report here

**Comment by SiddhantSadangi** [comment] 2024-03-19 08:53
Oh, you are referring to the local folder, not the folder created in the Neptune web app! Sorry for the confusion.

Could you share a code snippet for me to reproduce the issue?
I'd preferably need the snippets where you initialize `ModelCheckpoint`, `NeptuneLogger`, and `Trainer`

**Comment by SiddhantSadangi** [comment] 2024-03-19 08:56
Also, if you are syncing the runs with the Neptune servers, should it really matter where the models are saved locally pending upload?
Just curious

**Comment by AlexTo** [comment] 2024-03-26 13:16
@SiddhantSadangi sorry for late reply, I've been busy the last few days upgrading my code to Lightning 2.2 which makes this issue no longer applicable to me as this happens with ModelCheckpoint in Lightning 1.9.x only.
Actually my workflow is the opposite, I disabled uploading model checkpoints to the cloud as my models are quite large. Also I don't need to store on the cloud because the checkpoints are mostly for local evaluation and deployment. Only configuration and results are needed to store on Neptune servers.

**Comment by SiddhantSadangi** [comment] 2024-03-26 13:26
Perfect 🎉 
Looks like the issue was on Lightning's end, not ours.

I am closing this thread, but please feel free to reach out if you need any further support 🤗

**Closed by SiddhantSadangi** 2024-03-26 13:26 UTC
Labels: pending
