### ISSUE TITLE
BUG:  TypeError: object of type 'StringifyValue' has no len()

### ISSUE THREAD

**Issue by iirekm** [neptune-ai/neptune-client#1347] opened 2023-05-15 18:32 UTC
Version: `neptune = {extras = ["optuna"], version = "1.2.0"}`
Stacktrace: 
```
2023/05/15 20:19:32 |  
2023/05/15 20:19:32 | File "/root/.cache/pypoetry/virtualenvs/mono-build-jLCR1hfV-py3.8/lib/python3.8/site-packages/optuna/study/study.py", line 425, in optimize _optimize(
2023/05/15 20:19:32 |  
2023/05/15 20:19:32 | File "/root/.cache/pypoetry/virtualenvs/mono-build-jLCR1hfV-py3.8/lib/python3.8/site-packages/optuna/study/_optimize.py", line 103, in _optimize f.result()
2023/05/15 20:19:32 |  
2023/05/15 20:19:32 | File "/usr/lib/python3.8/concurrent/futures/_base.py", line 437, in result return self.__get_result()
2023/05/15 20:19:32 |  
2023/05/15 20:19:32 | File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result raise self._exception
2023/05/15 20:19:32 |  
2023/05/15 20:19:32 | File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run result = self.fn(*self.args, **self.kwargs)
2023/05/15 20:19:32 |  
2023/05/15 20:19:32 | File "/root/.cache/pypoetry/virtualenvs/mono-build-jLCR1hfV-py3.8/lib/python3.8/site-packages/optuna/study/_optimize.py", line 174, in _optimize_sequential callback(study, frozen_trial)
2023/05/15 20:19:32 |  
2023/05/15 20:19:32 | File "/root/.cache/pypoetry/virtualenvs/mono-build-jLCR1hfV-py3.8/lib/python3.8/site-packages/neptune_optuna/impl/__init__.py", line 197, in __call__ self._log_trial(study, trial)
2023/05/15 20:19:32 |  
2023/05/15 20:19:32 | File "/root/.cache/pypoetry/virtualenvs/mono-build-jLCR1hfV-py3.8/lib/python3.8/site-packages/neptune_optuna/impl/__init__.py", line 205, in _log_trial _log_single_trial(self.run, study, trial=trial, namespaces=self._namespaces)
2023/05/15 20:19:32 |  
2023/05/15 20:19:32 | File "/root/.cache/pypoetry/virtualenvs/mono-build-jLCR1hfV-py3.8/lib/python3.8/site-packages/neptune_optuna/impl/__init__.py", line 625, in _log_single_trial handle["values"].append(stringify_unsupported(trial.value), step=trial._trial_id)
2023/05/15 20:19:32 |  
2023/05/15 20:19:32 | File "/root/.cache/pypoetry/virtualenvs/mono-build-jLCR1hfV-py3.8/lib/python3.8/site-packages/neptune/handler.py", line 86, in inner_fun return fun(self, *args, **kwargs)
2023/05/15 20:19:32 |  
2023/05/15 20:19:32 | File "/root/.cache/pypoetry/virtualenvs/mono-build-jLCR1hfV-py3.8/lib/python3.8/site-packages/neptune/handler.py", line 392, in append self.extend(value, steps=step, timestamps=timestamp, wait=wait, **kwargs)
2023/05/15 20:19:32 |  
2023/05/15 20:19:32 | File "/root/.cache/pypoetry/virtualenvs/mono-build-jLCR1hfV-py3.8/lib/python3.8/site-packages/neptune/handler.py", line 86, in inner_fun return fun(self, *args, **kwargs)
2023/05/15 20:19:32 |  
2023/05/15 20:19:32 | File "/root/.cache/pypoetry/virtualenvs/mono-build-jLCR1hfV-py3.8/lib/python3.8/site-packages/neptune/handler.py", line 447, in extend attr.extend(values, steps=steps, timestamps=timestamps, wait=wait, **kwargs)
2023/05/15 20:19:32 |  
2023/05/15 20:19:32 | File "/root/.cache/pypoetry/virtualenvs/mono-build-jLCR1hfV-py3.8/lib/python3.8/site-packages/neptune/attributes/series/series.py", line 143, in extend if len(steps) != len(values):
2023/05/15 20:19:32 |  
2023/05/15 20:19:32 | TypeError: object of type 'StringifyValue' has no len()
2023/05/15 20:19:32
```

Calling code:
```python
            study = create_study()
            study.optimize(fn, n_jobs=-1, callbacks=[NeptuneCallback(run)], catch=Exception)
```

Maybe it's because of:
```
[33m[W 2023-05-15 18:05:50,021][0m Trial 2 failed with value None.[0m

[33m[W 2023-05-15 18:05:50,044][0m Trial 3 failed with value None.[0m
```
(optuna returns None in case of exception)

**Comment by Blaizzy** [comment] 2023-05-22 14:46
Hi @iirekm 

I believe that error is occurring because, since v1.0, we don't allow automatic conversion to a string of unsupported values such as `None`. 

Therefore, we suggest you explicitly convert any unsupported types to string. Either using Python's str() or our custom method [stringify_unsupported()](https://docs.neptune.ai/api/utils/#stringify_unsupported).

However, in your case, looking at the traceback, you are logging Series when the error occurs. Therefore, a potential solution would be to convert the `None` to `0`.

Example:
```python
if value == None:
     value = 0
```

Let me know if this works for you :)

**Comment by JohnorJohnny** [comment] 2023-06-01 10:08
![image](https://github.com/neptune-ai/neptune-client/assets/100992957/c32c878d-33ab-4c94-a92c-06288b4c7e69)
Same problem.
My oblective func return float number and when I remove 'stringify_unsuported()' from __init__.py it works

**Comment by Blaizzy** [comment] 2023-06-05 12:59
Thanks for the traceback, @JohnorJohnny!

It seems to be a bug with our integration.

Could you share a minimal reproducible example?

**Comment by JohnorJohnny** [comment] 2023-06-14 05:55
> Thanks for the traceback, @JohnorJohnny!
> 
> It seems to be a bug with our integration.
> 
> Could you share a minimal reproducible example?

Hi, this is a minimal reproducible example

https://gist.github.com/JohnorJohnny/c7dbac5c175796dd4107d64c0c69feee

**Comment by Blaizzy** [comment] 2023-06-14 12:23
I replicated the issue and discovered that you could solve it by upgrading to the latest version of Optuna -> 3.2.0.

`pip install -U optuna`

**Comment by Blaizzy** [comment] 2023-06-15 09:23
I'm closing the issue for now.

**Comment by SiddhantSadangi** [comment] 2023-06-16 10:49
Hello @iirekm , @JohnorJohnny

Thank you for reporting this issue.
We have forwarded this to our engineering team to have a look.

In the meanwhile, please let us know if there's anything else we can help you with :)

**Comment by SiddhantSadangi** [comment] 2023-06-26 08:27
While our developers take a look, here's a workaround:

1. Downgrade `neptune` to `neptune-client<1.0`: 

```bash
pip uninstall neptune neptune-client -y
pip install "neptune-client<1.0"
```

2. Update the import statements:
`import neptune` -> `import neptune.new as neptune`
`import neptune.integrations.optuna as optuna_utils` -> `import neptune.new.integrations.optuna as optuna_utils`

Once these changes are done, you should be able to use the Neptune-Optuna integration without any errors.

Please let me know if this works for you while we work on a more permanent fix 🙏

**Comment by SiddhantSadangi** [comment] 2023-07-05 10:48
Hello @iirekm , @JohnorJohnny 👋 

I have some good news 🤗 
The latest neptune release (v1.3.2) fixes this issue! 🎉 

I tested it against the code sample you had provided, and it worked fine.

Can you update neptune to 1.3.2 and let me know if it works for you too? 🙏

**Comment by wouterzwerink** [comment] 2023-07-12 17:04
Hi @SiddhantSadangi ! Upgrading solves this issue for me, but I run into a "No such file or directory: '.neptune/async/run...'" error. I'm fairly certain this is a similar bug to https://github.com/neptune-ai/neptune-client/issues/1379 and is caused by changing the .neptune directory location. Any workaround for this aside from not changing the directory location?

**Comment by SiddhantSadangi** [comment] 2023-07-13 09:51
Hello @wouterzwerink 👋 

Glad to know that the `StringifyValue` issue has been fixed. 🎉 

Regarding https://github.com/neptune-ai/neptune-client/issues/1379, the fix is currently in review (https://github.com/neptune-ai/neptune-client/pull/1391). I will update the thread as soon as it is released. ✅ 
However, I currently cannot offer you any workaround for this aside from not changing the directory location 😞 

Meanwhile, since [TypeError: object of type 'StringifyValue' has no len()](https://github.com/neptune-ai/neptune-client/issues/1347 ) has been fixed, I will close this.

**Closed by SiddhantSadangi** 2023-07-13 09:51 UTC
Labels: bug, pending

**Comment by wouterzwerink** [comment] 2023-07-13 09:56
@SiddhantSadangi thanks for the update! I did find a workaround actually. I symlinked the new .neptune folder location to `current_dir/.neptune`.

**Comment by SiddhantSadangi** [comment] 2023-07-13 10:02
ah, that's great 😃 

I'll take note in case someone else is also facing this issue ✍️ Thanks!

Hopefully, with #1391 , you won't have to adopt workarounds anymore :)
