### ISSUE TITLE
BUG: kedro neptune init fail

### ISSUE THREAD

**Issue by netphantom** [neptune-ai/neptune-client#1627] opened 2024-02-01 14:17 UTC
### Describe the bug
I am following the guide to integrate Neptune into my Kedro project but I am unable to run the command kedro neptune init. When I run it, I have the error:
KeyError: "No config patterns were found for 'credentials_neptune' in your config loader"

### Reproduction
I have an existing Kedro project, I run into the project folder and run the init command, provide the API and the project information

### Expected behavior
The initialized neptune project folder

### Traceback
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\kedro-project\venv\Scripts\kedro.exe\__main__.py", line 7, in <module>
  File "C:\Users\kedro-project\venv\Lib\site-packages\kedro\framework\cli\cli.py", line 211, in main
    cli_collection()
  File "C:\Users\kedro-project\venv\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kedro-project\venv\Lib\site-packages\kedro\framework\cli\cli.py", line 139, in main
    super().main(
  File "C:\Users\kedro-project\venv\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\kedro-project\venv\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kedro-project\venv\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kedro-project\venv\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kedro-project\venv\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kedro-project\venv\Lib\site-packages\click\decorators.py", line 45, in new_func
    return f(get_current_context().obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kedro-project\venv\Lib\site-packages\kedro_neptune\__init__.py", line 177, in init
    context = session.load_context()
              ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kedro-project\venv\Lib\site-packages\kedro\framework\session\session.py", line 284, in load_context
    self._hook_manager.hook.after_context_created(context=context)
  File "C:\Users\kedro-project\venv\Lib\site-packages\pluggy\_hooks.py", line 433, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kedro-project\venv\Lib\site-packages\pluggy\_manager.py", line 112, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kedro-project\venv\Lib\site-packages\pluggy\_manager.py", line 418, in traced_hookexec
    return outcome.get_result()
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kedro-project\venv\Lib\site-packages\pluggy\_result.py", line 108, in get_result
    raise exc.with_traceback(exc.__traceback__)
  File "C:\Users\kedro-project\venv\Lib\site-packages\pluggy\_result.py", line 70, in from_call
    result = func()
             ^^^^^^
  File "C:\Users\kedro-project\venv\Lib\site-packages\pluggy\_manager.py", line 415, in <lambda>
    lambda: oldcall(hook_name, hook_impls, caller_kwargs, firstresult)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kedro-project\venv\Lib\site-packages\pluggy\_callers.py", line 116, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "C:\Users\kedro-project\venv\Lib\site-packages\pluggy\_callers.py", line 80, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kedro-project\venv\Lib\site-packages\kedro_telemetry\plugin.py", line 128, in after_context_created
    catalog = context.catalog
              ^^^^^^^^^^^^^^^
  File "C:\Users\kedro-project\venv\Lib\site-packages\kedro\framework\context\context.py", line 226, in catalog
    return self._get_catalog()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kedro-project\venv\Lib\site-packages\kedro\framework\context\context.py", line 287, in _get_catalog
    self._hook_manager.hook.after_catalog_created(
  File "C:\Users\kedro-project\venv\Lib\site-packages\pluggy\_hooks.py", line 433, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kedro-project\venv\Lib\site-packages\pluggy\_manager.py", line 112, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kedro-project\venv\Lib\site-packages\pluggy\_manager.py", line 418, in traced_hookexec
    return outcome.get_result()
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kedro-project\venv\Lib\site-packages\pluggy\_result.py", line 108, in get_result
    raise exc.with_traceback(exc.__traceback__)
  File "C:\Users\kedro-project\venv\Lib\site-packages\pluggy\_result.py", line 70, in from_call
    result = func()
             ^^^^^^
  File "C:\Users\kedro-project\venv\Lib\site-packages\pluggy\_manager.py", line 415, in <lambda>
    lambda: oldcall(hook_name, hook_impls, caller_kwargs, firstresult)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kedro-project\venv\Lib\site-packages\pluggy\_callers.py", line 116, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "C:\Users\kedro-project\venv\Lib\site-packages\pluggy\_callers.py", line 80, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kedro-project\venv\Lib\site-packages\kedro_neptune\__init__.py", line 425, in after_catalog_created
    config = get_neptune_config(settings)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kedro-project\venv\Lib\site-packages\kedro_neptune\config.py", line 36, in get_neptune_config
    credentials = config_loader["credentials_neptune"]
                  ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kedro-project\venv\Lib\site-packages\kedro\config\omegaconf_config.py", line 182, in __getitem__
    raise KeyError(
KeyError: "No config patterns were found for 'credentials_neptune' in your config loader"

### Environment

```
Package                   Version
------------------------- ------------
aiobotocore               2.7.0
aiofiles                  23.2.1
aiohttp                   3.9.1
aioitertools              0.11.0
aiosignal                 1.3.1
antlr4-python3-runtime    4.9.3
anyconfig                 0.13.0
anyio                     3.7.1
argon2-cffi               23.1.0
argon2-cffi-bindings      21.2.0
arrow                     1.3.0
asttokens                 2.4.1
attrs                     23.1.0
Babel                     2.13.1
beautifulsoup4            4.12.2
binaryornot               0.4.4
black                     22.12.0
bleach                    6.1.0
boto3                     1.34.26
botocore                  1.34.26
bravado                   11.0.3
bravado-core              6.1.1
build                     1.0.3
bump2version              1.0.1
cachetools                5.3.2
certifi                   2023.7.22
cffi                      1.16.0
chardet                   5.2.0
charset-normalizer        3.3.2
click                     8.1.7
click-default-group       1.2.4
colorama                  0.4.6
comm                      0.2.0
contourpy                 1.2.0
cookiecutter              2.4.0
coverage                  7.3.2
cycler                    0.12.1
debugpy                   1.8.0
decorator                 5.1.1
defusedxml                0.7.1
dynaconf                  3.2.4
entrypoints               0.4
executing                 2.0.1
fastapi                   0.104.1
fastjsonschema            2.18.1
filelock                  3.13.1
flake8                    4.0.1
fonttools                 4.44.0
fqdn                      1.5.1
frozenlist                1.4.0
fsspec                    2023.10.0
future                    0.18.3
gitdb                     4.0.11
GitPython                 3.1.40
graphql-core              3.2.3
greenlet                  3.0.1
h11                       0.14.0
httptools                 0.6.1
idna                      3.4
importlib-metadata        6.8.0
importlib-resources       6.1.1
iniconfig                 2.0.0
ipykernel                 6.26.0
ipython                   8.17.2
ipython-genutils          0.2.0
ipywidgets                8.1.1
isoduration               20.11.0
isort                     5.12.0
jedi                      0.19.1
Jinja2                    3.1.2
jmespath                  1.0.1
joblib                    1.3.2
json5                     0.9.14
jsonpointer               2.4
jsonref                   1.1.0
jsonschema                4.19.2
jsonschema-specifications 2023.7.1
jupyter                   1.0.0
jupyter_client            7.4.9
jupyter-console           6.6.3
jupyter_core              5.5.0
jupyter-server            1.24.0
jupyterlab                3.5.3
jupyterlab-pygments       0.2.2
jupyterlab_server         2.15.2
jupyterlab-widgets        3.0.9
kedro                     0.18.14
kedro-datasets            1.8.0
kedro-neptune             0.3.0
kedro-telemetry           0.2.5
kedro-viz                 7.0.0
kiwisolver                1.4.5
lazy_loader               0.3
lightning-utilities       0.9.0
markdown-it-py            3.0.0
MarkupSafe                2.1.3
matplotlib                3.8.1
matplotlib-inline         0.1.6
mccabe                    0.6.1
mdurl                     0.1.2
mistune                   3.0.2
monotonic                 1.6
more-itertools            10.1.0
mpmath                    1.3.0
msgpack                   1.0.7
multidict                 6.0.4
mypy-extensions           1.0.0
nbclassic                 1.0.0
nbclient                  0.9.0
nbconvert                 7.11.0
nbformat                  5.9.2
nbstripout                0.6.1
neptune                   1.8.6
nest-asyncio              1.5.8
networkx                  3.2.1
notebook                  6.5.6
notebook_shim             0.2.3
numpy                     1.26.2
oauthlib                  3.2.2
omegaconf                 2.3.0
optree                    0.10.0
orjson                    3.9.10
packaging                 23.2
pandas                    2.1.3
pandocfilters             1.5.0
parse                     1.19.1
parso                     0.8.3
pathspec                  0.11.2
patsy                     0.5.3
Pillow                    10.1.0
pip                       23.3.2
pip-tools                 7.3.0
platformdirs              4.0.0
plotly                    5.18.0
pluggy                    1.2.0
prometheus-client         0.18.0
prompt-toolkit            3.0.40
psutil                    5.9.6
pure-eval                 0.2.2
pycodestyle               2.8.0
pycparser                 2.21
pydantic                  1.10.13
pyflakes                  2.4.0
Pygments                  2.16.1
PyJWT                     2.8.0
pyparsing                 3.1.1
pyproject_hooks           1.0.0
pytask                    0.4.2
pytest                    7.4.3
pytest-cov                3.0.0
pytest-mock               1.13.0
python-dateutil           2.8.2
python-dotenv             1.0.0
python-slugify            8.0.1
pytoolconfig              1.2.6
pytz                      2023.3.post1
pywin32                   306
pywinpty                  2.0.12
PyYAML                    6.0.1
pyzmq                     24.0.1
qtconsole                 5.5.0
QtPy                      2.4.1
referencing               0.30.2
requests                  2.31.0
requests-oauthlib         1.3.1
rfc3339-validator         0.1.4
rfc3986-validator         0.1.1
rich                      13.6.0
rope                      1.11.0
rpds-py                   0.12.0
ruamel.yaml               0.17.40
ruamel.yaml.clib          0.2.8
s3fs                      2023.10.0
s3transfer                0.10.0
scikit-learn              1.3.2
scipy                     1.11.3
seaborn                   0.12.2
secure                    0.3.0
Send2Trash                1.8.2
setuptools                68.2.0
simplejson                3.19.2
six                       1.16.0
smmap                     5.0.1
sniffio                   1.3.0
soupsieve                 2.5
SQLAlchemy                2.0.23
stack-data                0.6.3
starlette                 0.27.0
statsmodels               0.14.0
strawberry-graphql        0.215.1
swagger-spec-validator    3.0.3
sympy                     1.12
tenacity                  8.2.3
terminado                 0.18.0
text-unidecode            1.3
threadpoolctl             3.2.0
tinycss2                  1.2.1
toml                      0.10.2
tomli                     2.0.1
toposort                  1.10
torch                     2.1.0
torchmetrics              1.2.0
tornado                   6.3.3
traitlets                 5.9.0
types-python-dateutil     2.8.19.14
typing_extensions         4.8.0
tzdata                    2023.3
uri-template              1.3.0
urllib3                   2.0.7
uvicorn                   0.22.0
watchfiles                0.21.0
watchgod                  0.8.2
wcwidth                   0.2.9
webcolors                 1.13
webencodings              0.5.1
websocket-client          1.6.4
websockets                12.0
wheel                     0.41.2
widgetsnbextension        4.0.9
wrapt                     1.16.0
yarl                      1.9.3
zipp                      3.17.0
```
**The operating system you're using:** Windows 11

**The output of `python --version`:** Python 3.11.7

### Additional context
I used the Kedro internal versioning file before running the Neptune integration, could this influence the problem?

**Comment by SiddhantSadangi** [comment] 2024-02-01 14:23
Hey @netphantom 👋 

Looks like you have not added the config patterns needed to load the Neptune config to your project's `settings.py` -> `CONFIG_LOADER_ARGS`.

You will need to update `CONFIG_LOADER_ARGS` as below:

```
CONFIG_LOADER_ARGS = {
    ...,
    "config_patterns": {
        ...,
        "credentials_neptune" : ["credentials_neptune*"],
        "neptune": ["neptune*"],
    }
}
```

Here is the step-by-step installation and setup guide for `kedro-neptune`: https://docs.neptune.ai/integrations/kedro/

Please let me know if this helps, or if there is anything else I can help you with.

**Comment by netphantom** [comment] 2024-02-01 14:31
Hi @SiddhantSadangi , thank you for your welcome :).
I have updated the `CONFIG_LOADER_ARGS`, however as the init command fails, it does not create the yaml files in the config folders with the required credentials. As a matter of fact, if I add the `config_patterns` and I run the kedro neptune init, I have the following error:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\kedro-project\venv\Scripts\kedro.exe\__main__.py", line 7, in <module>
  File "C:\Users\kedro-project\venv\Lib\site-packages\kedro\framework\cli\cli.py", line 211, in main
    cli_collection()
  File "C:\Users\kedro-project\venv\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kedro-project\venv\Lib\site-packages\kedro\framework\cli\cli.py", line 139, in main
    super().main(
  File "C:\Users\kedro-project\venv\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\kedro-project\venv\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kedro-project\venv\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kedro-project\venv\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kedro-project\venv\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kedro-project\venv\Lib\site-packages\click\decorators.py", line 45, in new_func
    return f(get_current_context().obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kedro-project\venv\Lib\site-packages\kedro_neptune\__init__.py", line 177, in init
    context = session.load_context()
              ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kedro-project\venv\Lib\site-packages\kedro\framework\session\session.py", line 284, in load_context
    self._hook_manager.hook.after_context_created(context=context)
  File "C:\Users\kedro-project\venv\Lib\site-packages\pluggy\_hooks.py", line 433, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kedro-project\venv\Lib\site-packages\pluggy\_manager.py", line 112, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kedro-project\venv\Lib\site-packages\pluggy\_manager.py", line 418, in traced_hookexec
    return outcome.get_result()
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kedro-project\venv\Lib\site-packages\pluggy\_result.py", line 108, in get_result
    raise exc.with_traceback(exc.__traceback__)
  File "C:\Users\kedro-project\venv\Lib\site-packages\pluggy\_result.py", line 70, in from_call
    result = func()
             ^^^^^^
  File "C:\Users\kedro-project\venv\Lib\site-packages\pluggy\_manager.py", line 415, in <lambda>
    lambda: oldcall(hook_name, hook_impls, caller_kwargs, firstresult)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kedro-project\venv\Lib\site-packages\pluggy\_callers.py", line 116, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "C:\Users\kedro-project\venv\Lib\site-packages\pluggy\_callers.py", line 80, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kedro-project\venv\Lib\site-packages\kedro_telemetry\plugin.py", line 128, in after_context_created
    catalog = context.catalog
              ^^^^^^^^^^^^^^^
  File "C:\Users\kedro-project\venv\Lib\site-packages\kedro\framework\context\context.py", line 226, in catalog
    return self._get_catalog()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kedro-project\venv\Lib\site-packages\kedro\framework\context\context.py", line 287, in _get_catalog
    self._hook_manager.hook.after_catalog_created(
  File "C:\Users\kedro-project\venv\Lib\site-packages\pluggy\_hooks.py", line 433, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kedro-project\venv\Lib\site-packages\pluggy\_manager.py", line 112, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kedro-project\venv\Lib\site-packages\pluggy\_manager.py", line 418, in traced_hookexec
    return outcome.get_result()
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kedro-project\venv\Lib\site-packages\pluggy\_result.py", line 108, in get_result
    raise exc.with_traceback(exc.__traceback__)
  File "C:\Users\kedro-project\venv\Lib\site-packages\pluggy\_result.py", line 70, in from_call
    result = func()
             ^^^^^^
  File "C:\Users\kedro-project\venv\Lib\site-packages\pluggy\_manager.py", line 415, in <lambda>
    lambda: oldcall(hook_name, hook_impls, caller_kwargs, firstresult)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kedro-project\venv\Lib\site-packages\pluggy\_callers.py", line 116, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "C:\Users\kedro-project\venv\Lib\site-packages\pluggy\_callers.py", line 80, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kedro-project\venv\Lib\site-packages\kedro_neptune\__init__.py", line 425, in after_catalog_created
    config = get_neptune_config(settings)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kedro-project\venv\Lib\site-packages\kedro_neptune\config.py", line 37, in get_neptune_config
    config = config_loader["neptune"]
             ~~~~~~~~~~~~~^^^^^^^^^^^
  File "C:\Users\kedro-project\venv\Lib\site-packages\kedro\config\omegaconf_config.py", line 244, in __getitem__
    raise MissingConfigException(
kedro.config.abstract_config.MissingConfigException: No files of YAML or JSON format found in conf\base or conf\local matching the glob pattern(s): ['neptune*']


If I manually create the files, it keeps going with other errors/configurations missing

**Comment by SiddhantSadangi** [comment] 2024-02-01 14:40
Could you share the `config_patterns` you are using?
Looks like you might have missed adding the `*` at the end of `"neptune*"` :)

**Comment by netphantom** [comment] 2024-02-01 14:54
Sure, here it is:
`CONFIG_LOADER_ARGS = {
    "custom_resolvers": {
        "merge": merge_dicts,
    },
    "config_patterns": {
        "credentials_neptune": ["credentials_neptune*"],
        "neptune": ["neptune*"],
    }
}`

**Comment by SiddhantSadangi** [comment] 2024-02-01 15:36
Thats'weird.

I am not able to reproduce this issue.
Could you take me through the steps you followed, in order, while creating your kedro project, and share the structure of your project?

The `settings.py` file is used only for running the kedro project, and does not need to be updated before you run `kedro neptune init`.

Also, from your previous traceback, I would assume that the pattern in your `config_patterns` was `["neptune"]`, and not `["neptune*"]`, but that doesn't seem to be the case. Can you reconfirm that you are not able to run your project using the `config_patterns` you shared?

**Comment by netphantom** [comment] 2024-02-02 09:11
Hi @SiddhantSadangi, the steps I did were simple:
- Install with `pip install -U kedro-neptune` (I also tried `pip install -U "neptune[kedro]"` but it didn't change the procedure outcome)
- Then I run `kedro neptune init`, receiving the error I mentioned.

I cloned the same repository I am using on a Linux (Manjaro) machine, run `kedro neptune init` and everything worked perfectly. 

It seems to be some weirdo Windows problem, I don't know where to look to solve this. By the way this is the project structure:

```
.
├── conf
│   ├── base
│   │   ├── catalog.yml
│   │   ├── logging.yml
│   │   ├── parameters_pipeline1.yml
│   │   ├── parameters_pipeline2.yml
│   │   ├── parameters_pipeline3.yml
│   │   ├── parameters_pipeline4.yml
│   │   └── parameters.yml
│   ├── local
│   │   └── credentials.yml
│   └── README.md
├── docs
│   └── source
│       ├── conf.py
│       └── index.rst
├── info.log
├── notebooks
├── pyproject.toml
├── README.md
├── src
│   ├── lstm
│   │   ├── extras
│   │   │   ├── dataset
│   │   │   │   ├── __init__.py
│   │   │   │   └── torch_set.py
│   │   │   └── __init__.py
│   │   ├── __init__.py
│   │   ├── __main__.py
│   │   ├── pipeline_registry.py
│   │   ├── pipelines
│   │   │   ├── pipeline1
│   │   │   │   ├── accessories.py
│   │   │   │   ├── __init__.py
│   │   │   │   ├── nodes.py
│   │   │   │   └── pipeline.py
│   │   │   ├── __init__.py
│   │   │   ├── pipeline2
│   │   │   │   ├── __init__.py
│   │   │   │   ├── nodes.py
│   │   │   │   └── pipeline.py
│   │   │   ├── pipeline3
│   │   │   │   ├── __init__.py
│   │   │   │   ├── nodes.py
│   │   │   │   └── pipeline.py
│   │   │   └── pipeline4
│   │   │       ├── __init__.py
│   │   │       ├── nodes.py
│   │   │       └── pipeline.py
│   │   └── settings.py
│   ├── pyproject.toml
│   ├── requirements.txt
│   ├── tests
│   │   ├── __init__.py
│   │   ├── pipelines
│   │   │   ├── pipeline1
│   │   │   │   ├── __init__.py
│   │   │   │   └── test_pipeline.py
│   │   │   ├── __init__.py
│   │   │   ├── pipeline2
│   │   │   │   ├── __init__.py
│   │   │   │   └── test_pipeline.py
│   │   │   ├── pipeline3
│   │   │   │   ├── __init__.py
│   │   │   │   └── test_pipeline.py
│   │   │   └── pipeline4
│   │   │       ├── __init__.py
│   │   │       └── test_pipeline.py
│   │   └── test_run.py
│   └── utilities
│       ├── data.py
│       ├── __init__.py
│       ├── model.py
│       ├── plotting.py
│       ├── testing.py
│       └── training.py
└── stats.json
```

**Comment by SiddhantSadangi** [comment] 2024-02-02 09:56
I am not able to reproduce this error on a Windows machine too 😔 

Would it be possible for you to share a minimal project (as a ZIP file, or a GitHub repo) that I can use to reproduce this?

**Comment by SiddhantSadangi** [comment] 2024-02-02 09:57
Can you also try upgrading kedro to the latest version - 0.19.2?

**Comment by netphantom** [comment] 2024-02-02 10:50
Unfortunately I cannot share the code and the project I am using as there are sensible information. 

However, I just tried the simpliest thing: I removed and reinstalled kedro and kedro-telemetry (always the 0.18.14, due to catalog compatibility issues), run kedro neptune init... and it worked. So, I could imagine that the problem was some dirty in the python venv.

**Comment by SiddhantSadangi** [comment] 2024-02-02 11:05
Glad that you were able to get this resolved! 🎉 

Since it seems to be an issue with `kedro`/`kedro-telemetry`, can you try raising an issue in [kedro](https://github.com/kedro-org/kedro/issues)?

Meanwhile, I am closing this. But please feel free to reopen or comment if need be 🤗

**Closed by SiddhantSadangi** 2024-02-02 11:05 UTC
Labels: pending
