### ISSUE TITLE
Neptune Client Library was not able to resolve hostname ui.neptune.ml

### ISSUE THREAD

**Issue by wjaskowski** [neptune-ai/neptune-client#589] opened 2021-06-08 09:00 UTC
I have got such a random error on resuming a run. This is problematic to me since I conduct a number of resumes during a single experiment (a number of parallel workers) so if such a resume fails, everything fails. I am not sure whether this could be somehow solved in Neptune or I need to provide robustness on my own.

neptune-client 0.9.16

```python
2021/06/08 02:14:40 | Marking run as failed
2021/06/08 02:14:40 | Traceback:
[...]
2021/06/08 02:14:40 | with neptune.init(
2021/06/08 02:14:40 | File "/home/wojciech/miniconda3/envs/nori/lib/python3.8/site-packages/neptune/new/internal/init_impl.py", line 230, in init
2021/06/08 02:14:40 | backend = HostedNeptuneBackend(
2021/06/08 02:14:40 | File "/home/wojciech/miniconda3/envs/nori/lib/python3.8/site-packages/neptune/new/internal/backends/hosted_neptune_backend.py", line 132, in __init__
2021/06/08 02:14:40 | verify_host_resolution(config_api_url)
2021/06/08 02:14:40 | File "/home/wojciech/miniconda3/envs/nori/lib/python3.8/site-packages/neptune/new/internal/backends/utils.py", line 109, in verify_host_resolution
2021/06/08 02:14:40 | raise CannotResolveHostname(host)
2021/06/08 02:14:40 | neptune.new.exceptions.CannotResolveHostname:
2021/06/08 02:14:40 | [95m
2021/06/08 02:14:40 | ----CannotResolveHostname-----------------------------------------------------------------------
2021/06/08 02:14:40 | [0m
2021/06/08 02:14:40 | Neptune Client Library was not able to resolve hostname [4mui.neptune.ml[0m.
2021/06/08 02:14:40 | &nbsp;
2021/06/08 02:14:40 | What should I do?
2021/06/08 02:14:40 | - Check if your computer is connected to the internet.
2021/06/08 02:14:40 | - Check if your computer should use any proxy to access internet.
2021/06/08 02:14:40 | If so, you may want to use [96mproxies[0m parameter of [96mneptune.init()[0m function.
2021/06/08 02:14:40 | See https://docs.neptune.ai/api-reference/neptune#init
2021/06/08 02:14:40 | and https://requests.readthedocs.io/en/master/user/advanced/#proxies
2021/06/08 02:14:40 | &nbsp;
2021/06/08 02:14:40 | [92mNeed help?[0m-&gt; https://docs.neptune.ai/getting-started/getting-help
```

**Comment by Herudaio** [comment] 2021-06-08 09:19
@wjaskowski `ui.neptune.ml` suggests that this is a very old API token (API token is a combination of token + address). The troubling part is that it happens randomly.

Could you go to app.neptune.ai and without entering any project space and copy your API token from the Help Center or Context switcher and update it in relevant places?
(entering project in legacy structure will switch domain to ui.neptune.ai and that domain would be embedded in API token)

**Comment by pkasprzyk** [comment] 2021-08-11 06:43
closing as not a bug

**Closed by pkasprzyk** 2021-08-11 06:43 UTC
